export type NutritionStatus = "Normal" | "Underweight" | "Overweight" | "At Risk";

export interface Student {
  id: string;
  lrn: string;
  name: string;
  grade: string;
  section: string;
  sex: "Male" | "Female";
  dob: string;
  guardian: string;
  beneficiary: boolean;
  allergy: boolean;
  allergyNotes?: string;
  baselineBMI: number;
  endlineBMI: number;
  baselineStatus: NutritionStatus;
  endlineStatus: NutritionStatus;
}

export const students: Student[] = [
  // Grade 1 - Sampaguita
  {
    id: "S-1001",
    lrn: "136521090001",
    name: "Andrea Cruz",
    grade: "Grade 1",
    section: "Sampaguita",
    sex: "Female",
    dob: "2017-03-12",
    guardian: "Liza Cruz",
    beneficiary: true,
    allergy: false,
    baselineBMI: 13.2,
    endlineBMI: 14.6,
    baselineStatus: "Underweight",
    endlineStatus: "Normal",
  },
  {
    id: "S-1002",
    lrn: "136521090002",
    name: "Daniel Reyes",
    grade: "Grade 1",
    section: "Sampaguita",
    sex: "Male",
    dob: "2017-01-18",
    guardian: "Anna Reyes",
    beneficiary: false,
    allergy: false,
    baselineBMI: 19.5,
    endlineBMI: 19.2,
    baselineStatus: "Overweight",
    endlineStatus: "Normal",
  },
  {
    id: "S-1003",
    lrn: "136521090003",
    name: "Miguel Garcia",
    grade: "Grade 1",
    section: "Sampaguita",
    sex: "Male",
    dob: "2017-06-08",
    guardian: "Carlos Garcia",
    beneficiary: true,
    allergy: false,
    baselineBMI: 14.8,
    endlineBMI: 15.3,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-1004",
    lrn: "136521090004",
    name: "Sofia Bautista",
    grade: "Grade 1",
    section: "Sampaguita",
    sex: "Female",
    dob: "2017-09-14",
    guardian: "Elena Bautista",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Eggs",
    baselineBMI: 12.9,
    endlineBMI: 13.8,
    baselineStatus: "Underweight",
    endlineStatus: "At Risk",
  },
  {
    id: "S-1005",
    lrn: "136521090005",
    name: "Lucas Morales",
    grade: "Grade 1",
    section: "Sampaguita",
    sex: "Male",
    dob: "2017-04-22",
    guardian: "Rosa Morales",
    beneficiary: true,
    allergy: false,
    baselineBMI: 15.1,
    endlineBMI: 15.7,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-1006",
    lrn: "136521090006",
    name: "Isabella Flores",
    grade: "Grade 1",
    section: "Sampaguita",
    sex: "Female",
    dob: "2017-11-30",
    guardian: "Maria Flores",
    beneficiary: false,
    allergy: false,
    baselineBMI: 17.2,
    endlineBMI: 16.9,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-1007",
    lrn: "136521090007",
    name: "Ethan Santos",
    grade: "Grade 1",
    section: "Sampaguita",
    sex: "Male",
    dob: "2017-02-05",
    guardian: "Luis Santos",
    beneficiary: true,
    allergy: false,
    baselineBMI: 13.7,
    endlineBMI: 14.5,
    baselineStatus: "At Risk",
    endlineStatus: "Normal",
  },
  {
    id: "S-1008",
    lrn: "136521090008",
    name: "Ava Hernandez",
    grade: "Grade 1",
    section: "Sampaguita",
    sex: "Female",
    dob: "2017-07-19",
    guardian: "Pedro Hernandez",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Milk",
    baselineBMI: 12.3,
    endlineBMI: 13.1,
    baselineStatus: "Underweight",
    endlineStatus: "Underweight",
  },

  // Grade 2 - Rosal
  {
    id: "S-2001",
    lrn: "136521090009",
    name: "Benjie Santos",
    grade: "Grade 2",
    section: "Rosal",
    sex: "Male",
    dob: "2016-07-22",
    guardian: "Mario Santos",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Peanuts",
    baselineBMI: 12.8,
    endlineBMI: 13.4,
    baselineStatus: "Underweight",
    endlineStatus: "Underweight",
  },
  {
    id: "S-2002",
    lrn: "136521090010",
    name: "Francisco Lim",
    grade: "Grade 2",
    section: "Rosal",
    sex: "Male",
    dob: "2016-09-09",
    guardian: "Marisol Lim",
    beneficiary: true,
    allergy: false,
    baselineBMI: 13.9,
    endlineBMI: 14.8,
    baselineStatus: "At Risk",
    endlineStatus: "Normal",
  },
  {
    id: "S-2003",
    lrn: "136521090011",
    name: "Angelica Torres",
    grade: "Grade 2",
    section: "Rosal",
    sex: "Female",
    dob: "2016-12-03",
    guardian: "Roberto Torres",
    beneficiary: true,
    allergy: false,
    baselineBMI: 14.6,
    endlineBMI: 15.2,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-2004",
    lrn: "136521090012",
    name: "Joshua Castro",
    grade: "Grade 2",
    section: "Rosal",
    sex: "Male",
    dob: "2016-05-16",
    guardian: "Carmen Castro",
    beneficiary: false,
    allergy: false,
    baselineBMI: 16.4,
    endlineBMI: 16.8,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-2005",
    lrn: "136521090013",
    name: "Gabriella Ramos",
    grade: "Grade 2",
    section: "Rosal",
    sex: "Female",
    dob: "2016-08-27",
    guardian: "Fernando Ramos",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Shellfish",
    baselineBMI: 13.2,
    endlineBMI: 14.1,
    baselineStatus: "Underweight",
    endlineStatus: "At Risk",
  },
  {
    id: "S-2006",
    lrn: "136521090014",
    name: "Nathaniel Alvarez",
    grade: "Grade 2",
    section: "Rosal",
    sex: "Male",
    dob: "2016-10-11",
    guardian: "Gloria Alvarez",
    beneficiary: true,
    allergy: false,
    baselineBMI: 15.8,
    endlineBMI: 16.3,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-2007",
    lrn: "136521090015",
    name: "Victoria Mendoza",
    grade: "Grade 2",
    section: "Rosal",
    sex: "Female",
    dob: "2016-03-08",
    guardian: "Antonio Mendoza",
    beneficiary: true,
    allergy: false,
    baselineBMI: 12.7,
    endlineBMI: 13.9,
    baselineStatus: "Underweight",
    endlineStatus: "At Risk",
  },
  {
    id: "S-2008",
    lrn: "136521090016",
    name: "Christian dela Cruz",
    grade: "Grade 2",
    section: "Rosal",
    sex: "Male",
    dob: "2016-01-25",
    guardian: "Juana dela Cruz",
    beneficiary: false,
    allergy: false,
    baselineBMI: 18.1,
    endlineBMI: 17.8,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },

  // Grade 3 - Ilang-Ilang
  {
    id: "S-3001",
    lrn: "136521090017",
    name: "Camille Dela Rosa",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    sex: "Female",
    dob: "2015-11-04",
    guardian: "Rosa Dela Rosa",
    beneficiary: true,
    allergy: false,
    baselineBMI: 16.8,
    endlineBMI: 17.1,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-3002",
    lrn: "136521090018",
    name: "Hector Villanueva",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    sex: "Male",
    dob: "2015-04-25",
    guardian: "Patricia V.",
    beneficiary: true,
    allergy: false,
    baselineBMI: 12.4,
    endlineBMI: 13.6,
    baselineStatus: "Underweight",
    endlineStatus: "At Risk",
  },
  {
    id: "S-3003",
    lrn: "136521090019",
    name: "Sophia Aguilar",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    sex: "Female",
    dob: "2015-06-13",
    guardian: "Miguel Aguilar",
    beneficiary: true,
    allergy: false,
    baselineBMI: 15.4,
    endlineBMI: 16.1,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-3004",
    lrn: "136521090020",
    name: "Jacob Romero",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    sex: "Male",
    dob: "2015-09-30",
    guardian: "Isabel Romero",
    beneficiary: false,
    allergy: false,
    baselineBMI: 17.6,
    endlineBMI: 17.9,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-3005",
    lrn: "136521090021",
    name: "Natalie Fernandez",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    sex: "Female",
    dob: "2015-02-17",
    guardian: "Rafael Fernandez",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Wheat",
    baselineBMI: 13.8,
    endlineBMI: 14.7,
    baselineStatus: "At Risk",
    endlineStatus: "Normal",
  },
  {
    id: "S-3006",
    lrn: "136521090022",
    name: "Alexander Guzman",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    sex: "Male",
    dob: "2015-07-08",
    guardian: "Teresa Guzman",
    beneficiary: true,
    allergy: false,
    baselineBMI: 14.2,
    endlineBMI: 14.9,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-3007",
    lrn: "136521090023",
    name: "Emily Navarro",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    sex: "Female",
    dob: "2015-12-21",
    guardian: "Pedro Navarro",
    beneficiary: true,
    allergy: false,
    baselineBMI: 12.1,
    endlineBMI: 13.3,
    baselineStatus: "Underweight",
    endlineStatus: "Underweight",
  },
  {
    id: "S-3008",
    lrn: "136521090024",
    name: "Michael Santiago",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    sex: "Male",
    dob: "2015-01-14",
    guardian: "Lourdes Santiago",
    beneficiary: false,
    allergy: false,
    baselineBMI: 19.1,
    endlineBMI: 18.7,
    baselineStatus: "Overweight",
    endlineStatus: "Normal",
  },

  // Grade 4 - Orchid
  {
    id: "S-4001",
    lrn: "136521090025",
    name: "Elaine Mendoza",
    grade: "Grade 4",
    section: "Orchid",
    sex: "Female",
    dob: "2014-05-30",
    guardian: "Joel Mendoza",
    beneficiary: true,
    allergy: false,
    baselineBMI: 14.1,
    endlineBMI: 15.2,
    baselineStatus: "At Risk",
    endlineStatus: "Normal",
  },
  {
    id: "S-4002",
    lrn: "136521090026",
    name: "Raphael Vasquez",
    grade: "Grade 4",
    section: "Orchid",
    sex: "Male",
    dob: "2014-08-19",
    guardian: "Angela Vasquez",
    beneficiary: true,
    allergy: false,
    baselineBMI: 15.9,
    endlineBMI: 16.5,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-4003",
    lrn: "136521090027",
    name: "Chloe Domingo",
    grade: "Grade 4",
    section: "Orchid",
    sex: "Female",
    dob: "2014-03-11",
    guardian: "Manuel Domingo",
    beneficiary: false,
    allergy: true,
    allergyNotes: "Nuts",
    baselineBMI: 17.3,
    endlineBMI: 17.0,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-4004",
    lrn: "136521090028",
    name: "Sebastian Cortez",
    grade: "Grade 4",
    section: "Orchid",
    sex: "Male",
    dob: "2014-10-05",
    guardian: "Diana Cortez",
    beneficiary: true,
    allergy: false,
    baselineBMI: 13.4,
    endlineBMI: 14.6,
    baselineStatus: "Underweight",
    endlineStatus: "Normal",
  },
  {
    id: "S-4005",
    lrn: "136521090029",
    name: "Madison Reyes",
    grade: "Grade 4",
    section: "Orchid",
    sex: "Female",
    dob: "2014-06-28",
    guardian: "Roberto Reyes",
    beneficiary: true,
    allergy: false,
    baselineBMI: 16.2,
    endlineBMI: 16.8,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-4006",
    lrn: "136521090030",
    name: "Leonardo Padilla",
    grade: "Grade 4",
    section: "Orchid",
    sex: "Male",
    dob: "2014-01-09",
    guardian: "Carmen Padilla",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Soy",
    baselineBMI: 12.6,
    endlineBMI: 13.8,
    baselineStatus: "Underweight",
    endlineStatus: "At Risk",
  },
  {
    id: "S-4007",
    lrn: "136521090031",
    name: "Hannah Guerrero",
    grade: "Grade 4",
    section: "Orchid",
    sex: "Female",
    dob: "2014-11-22",
    guardian: "Francisco Guerrero",
    beneficiary: false,
    allergy: false,
    baselineBMI: 18.4,
    endlineBMI: 18.1,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-4008",
    lrn: "136521090032",
    name: "Adrian Luna",
    grade: "Grade 4",
    section: "Orchid",
    sex: "Male",
    dob: "2014-04-16",
    guardian: "Maria Luna",
    beneficiary: true,
    allergy: false,
    baselineBMI: 14.7,
    endlineBMI: 15.4,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },

  // Grade 5 - Camia
  {
    id: "S-5001",
    lrn: "136521090033",
    name: "Gianna Tan",
    grade: "Grade 5",
    section: "Camia",
    sex: "Female",
    dob: "2013-12-12",
    guardian: "Erik Tan",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Seafood",
    baselineBMI: 15.2,
    endlineBMI: 16.0,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-5002",
    lrn: "136521090034",
    name: "Matthew Acosta",
    grade: "Grade 5",
    section: "Camia",
    sex: "Male",
    dob: "2013-09-03",
    guardian: "Patricia Acosta",
    beneficiary: true,
    allergy: false,
    baselineBMI: 16.7,
    endlineBMI: 17.2,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-5003",
    lrn: "136521090035",
    name: "Zoe Martinez",
    grade: "Grade 5",
    section: "Camia",
    sex: "Female",
    dob: "2013-05-27",
    guardian: "Antonio Martinez",
    beneficiary: false,
    allergy: false,
    baselineBMI: 18.9,
    endlineBMI: 18.6,
    baselineStatus: "Overweight",
    endlineStatus: "Normal",
  },
  {
    id: "S-5004",
    lrn: "136521090036",
    name: "Dylan Castillo",
    grade: "Grade 5",
    section: "Camia",
    sex: "Male",
    dob: "2013-07-14",
    guardian: "Rosa Castillo",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Dairy",
    baselineBMI: 13.1,
    endlineBMI: 14.3,
    baselineStatus: "Underweight",
    endlineStatus: "At Risk",
  },
  {
    id: "S-5005",
    lrn: "136521090037",
    name: "Lily Morales",
    grade: "Grade 5",
    section: "Camia",
    sex: "Female",
    dob: "2013-02-08",
    guardian: "Carlos Morales",
    beneficiary: true,
    allergy: false,
    baselineBMI: 14.9,
    endlineBMI: 15.6,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-5006",
    lrn: "136521090038",
    name: "Jayden Rivera",
    grade: "Grade 5",
    section: "Camia",
    sex: "Male",
    dob: "2013-10-31",
    guardian: "Elena Rivera",
    beneficiary: true,
    allergy: false,
    baselineBMI: 15.7,
    endlineBMI: 16.4,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-5007",
    lrn: "136521090039",
    name: "Savannah Ortiz",
    grade: "Grade 5",
    section: "Camia",
    sex: "Female",
    dob: "2013-04-19",
    guardian: "Miguel Ortiz",
    beneficiary: false,
    allergy: false,
    baselineBMI: 17.8,
    endlineBMI: 17.5,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-5008",
    lrn: "136521090040",
    name: "Carter Ramirez",
    grade: "Grade 5",
    section: "Camia",
    sex: "Male",
    dob: "2013-01-23",
    guardian: "Gloria Ramirez",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Fish",
    baselineBMI: 12.9,
    endlineBMI: 13.7,
    baselineStatus: "Underweight",
    endlineStatus: "Underweight",
  },

  // Grade 6 - Daisy
  {
    id: "S-6001",
    lrn: "136521090041",
    name: "Jasmine Bautista",
    grade: "Grade 6",
    section: "Daisy",
    sex: "Female",
    dob: "2012-08-15",
    guardian: "Ramon Bautista",
    beneficiary: true,
    allergy: false,
    baselineBMI: 16.1,
    endlineBMI: 16.8,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-6002",
    lrn: "136521090042",
    name: "Ryan Cabrera",
    grade: "Grade 6",
    section: "Daisy",
    sex: "Male",
    dob: "2012-11-07",
    guardian: "Luisa Cabrera",
    beneficiary: false,
    allergy: false,
    baselineBMI: 19.3,
    endlineBMI: 19.0,
    baselineStatus: "Overweight",
    endlineStatus: "Normal",
  },
  {
    id: "S-6003",
    lrn: "136521090043",
    name: "Ariana Vega",
    grade: "Grade 6",
    section: "Daisy",
    sex: "Female",
    dob: "2012-06-29",
    guardian: "Fernando Vega",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Citrus",
    baselineBMI: 14.4,
    endlineBMI: 15.2,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-6004",
    lrn: "136521090044",
    name: "Connor Medina",
    grade: "Grade 6",
    section: "Daisy",
    sex: "Male",
    dob: "2012-03-12",
    guardian: "Teresa Medina",
    beneficiary: true,
    allergy: false,
    baselineBMI: 13.6,
    endlineBMI: 14.8,
    baselineStatus: "At Risk",
    endlineStatus: "Normal",
  },
  {
    id: "S-6005",
    lrn: "136521090045",
    name: "Genesis Flores",
    grade: "Grade 6",
    section: "Daisy",
    sex: "Female",
    dob: "2012-09-24",
    guardian: "Pedro Flores",
    beneficiary: true,
    allergy: false,
    baselineBMI: 15.3,
    endlineBMI: 16.1,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-6006",
    lrn: "136521090046",
    name: "Parker Santos",
    grade: "Grade 6",
    section: "Daisy",
    sex: "Male",
    dob: "2012-12-18",
    guardian: "Maria Santos",
    beneficiary: false,
    allergy: false,
    baselineBMI: 18.2,
    endlineBMI: 17.9,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-6007",
    lrn: "136521090047",
    name: "Bella Gonzales",
    grade: "Grade 6",
    section: "Daisy",
    sex: "Female",
    dob: "2012-05-06",
    guardian: "Jose Gonzales",
    beneficiary: true,
    allergy: true,
    allergyNotes: "Chocolate",
    baselineBMI: 12.8,
    endlineBMI: 14.0,
    baselineStatus: "Underweight",
    endlineStatus: "At Risk",
  },
  {
    id: "S-6008",
    lrn: "136521090048",
    name: "Grayson Torres",
    grade: "Grade 6",
    section: "Daisy",
    sex: "Male",
    dob: "2012-01-30",
    guardian: "Ana Torres",
    beneficiary: true,
    allergy: false,
    baselineBMI: 17.1,
    endlineBMI: 17.6,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },

  // Additional students to reach 50+ total
  {
    id: "S-1009",
    lrn: "136521090049",
    name: "Luna Castillo",
    grade: "Grade 1",
    section: "Sampaguita",
    sex: "Female",
    dob: "2017-08-03",
    guardian: "Diego Castillo",
    beneficiary: true,
    allergy: false,
    baselineBMI: 14.3,
    endlineBMI: 15.1,
    baselineStatus: "Normal",
    endlineStatus: "Normal",
  },
  {
    id: "S-2009",
    lrn: "136521090050",
    name: "Nova Aguilar",
    grade: "Grade 2",
    section: "Rosal",
    sex: "Female",
    dob: "2016-04-12",
    guardian: "Javier Aguilar",
    beneficiary: true,
    allergy: false,
    baselineBMI: 13.5,
    endlineBMI: 14.4,
    baselineStatus: "At Risk",
    endlineStatus: "Normal",
  },
];

export const grades = ["Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6"];
export const sections = ["Sampaguita", "Rosal", "Ilang-Ilang", "Orchid", "Camia", "Daisy"];

export const statusColor: Record<NutritionStatus, string> = {
  Normal: "bg-success/15 text-success border-success/30",
  Underweight: "bg-destructive/15 text-destructive border-destructive/30",
  Overweight: "bg-warning/20 text-warning-foreground border-warning/40",
  "At Risk": "bg-warning/15 text-warning-foreground border-warning/40",
};

export function computeBMI(heightCm: number, weightKg: number): number {
  if (!heightCm || !weightKg) return 0;
  const m = heightCm / 100;
  return +(weightKg / (m * m)).toFixed(2);
}

export function classifyBMI(bmi: number): NutritionStatus {
  if (bmi < 13) return "Underweight";
  if (bmi < 14.5) return "At Risk";
  if (bmi <= 18) return "Normal";
  return "Overweight";
}

export interface MeasurementRecord {
  id: string;
  studentId: string;
  date: string;
  type: "Baseline" | "Endline" | "Follow-up";
  height: number;
  weight: number;
  bmi: number;
  status: NutritionStatus;
  recordedBy: string;
  notes?: string;
}

export const measurementRecords: MeasurementRecord[] = [
  // Grade 1 - Sampaguita
  {
    id: "M-1001-B",
    studentId: "S-1001",
    date: "2025-01-15",
    type: "Baseline",
    height: 110,
    weight: 16.0,
    bmi: 13.22,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Initial assessment",
  },
  {
    id: "M-1001-E",
    studentId: "S-1001",
    date: "2025-04-20",
    type: "Endline",
    height: 113,
    weight: 18.6,
    bmi: 14.57,
    status: "Normal",
    recordedBy: "Maria Reyes",
    notes: "Good progress",
  },
  {
    id: "M-1002-B",
    studentId: "S-1002",
    date: "2025-01-15",
    type: "Baseline",
    height: 108,
    weight: 18.2,
    bmi: 15.58,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1002-E",
    studentId: "S-1002",
    date: "2025-04-20",
    type: "Endline",
    height: 111,
    weight: 18.8,
    bmi: 15.25,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1003-B",
    studentId: "S-1003",
    date: "2025-01-15",
    type: "Baseline",
    height: 109,
    weight: 17.8,
    bmi: 14.98,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1003-E",
    studentId: "S-1003",
    date: "2025-04-20",
    type: "Endline",
    height: 112,
    weight: 19.1,
    bmi: 15.21,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1004-B",
    studentId: "S-1004",
    date: "2025-01-15",
    type: "Baseline",
    height: 107,
    weight: 14.8,
    bmi: 12.96,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Egg allergy noted",
  },
  {
    id: "M-1004-E",
    studentId: "S-1004",
    date: "2025-04-20",
    type: "Endline",
    height: 110,
    weight: 16.7,
    bmi: 13.79,
    status: "At Risk",
    recordedBy: "Maria Reyes",
    notes: "Slow progress, needs intervention",
  },
  {
    id: "M-1005-B",
    studentId: "S-1005",
    date: "2025-01-15",
    type: "Baseline",
    height: 111,
    weight: 18.5,
    bmi: 15.01,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1005-E",
    studentId: "S-1005",
    date: "2025-04-20",
    type: "Endline",
    height: 114,
    weight: 20.1,
    bmi: 15.42,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1006-B",
    studentId: "S-1006",
    date: "2025-01-15",
    type: "Baseline",
    height: 112,
    weight: 21.5,
    bmi: 17.14,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1006-E",
    studentId: "S-1006",
    date: "2025-04-20",
    type: "Endline",
    height: 115,
    weight: 21.8,
    bmi: 16.48,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1007-B",
    studentId: "S-1007",
    date: "2025-01-15",
    type: "Baseline",
    height: 106,
    weight: 15.2,
    bmi: 13.52,
    status: "At Risk",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1007-E",
    studentId: "S-1007",
    date: "2025-04-20",
    type: "Endline",
    height: 109,
    weight: 17.3,
    bmi: 14.56,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1008-B",
    studentId: "S-1008",
    date: "2025-01-15",
    type: "Baseline",
    height: 105,
    weight: 13.6,
    bmi: 12.33,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Milk allergy noted",
  },
  {
    id: "M-1008-E",
    studentId: "S-1008",
    date: "2025-04-20",
    type: "Endline",
    height: 108,
    weight: 15.2,
    bmi: 13.07,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Still underweight, continue monitoring",
  },
  {
    id: "M-1009-B",
    studentId: "S-1009",
    date: "2025-01-15",
    type: "Baseline",
    height: 110,
    weight: 17.3,
    bmi: 14.31,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-1009-E",
    studentId: "S-1009",
    date: "2025-04-20",
    type: "Endline",
    height: 113,
    weight: 19.1,
    bmi: 14.94,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },

  // Grade 2 - Rosal
  {
    id: "M-2001-B",
    studentId: "S-2001",
    date: "2025-01-15",
    type: "Baseline",
    height: 115,
    weight: 15.2,
    bmi: 11.51,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Peanut allergy noted",
  },
  {
    id: "M-2001-E",
    studentId: "S-2001",
    date: "2025-04-20",
    type: "Endline",
    height: 118,
    weight: 16.8,
    bmi: 12.06,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Minimal improvement",
  },
  {
    id: "M-2002-B",
    studentId: "S-2002",
    date: "2025-01-15",
    type: "Baseline",
    height: 117,
    weight: 19.0,
    bmi: 13.88,
    status: "At Risk",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2002-E",
    studentId: "S-2002",
    date: "2025-04-20",
    type: "Endline",
    height: 120,
    weight: 21.3,
    bmi: 14.76,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2003-B",
    studentId: "S-2003",
    date: "2025-01-15",
    type: "Baseline",
    height: 116,
    weight: 19.8,
    bmi: 14.69,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2003-E",
    studentId: "S-2003",
    date: "2025-04-20",
    type: "Endline",
    height: 119,
    weight: 21.6,
    bmi: 15.22,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2004-B",
    studentId: "S-2004",
    date: "2025-01-15",
    type: "Baseline",
    height: 118,
    weight: 21.8,
    bmi: 15.63,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2004-E",
    studentId: "S-2004",
    date: "2025-04-20",
    type: "Endline",
    height: 121,
    weight: 23.1,
    bmi: 15.78,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2005-B",
    studentId: "S-2005",
    date: "2025-01-15",
    type: "Baseline",
    height: 114,
    weight: 16.8,
    bmi: 12.89,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Shellfish allergy noted",
  },
  {
    id: "M-2005-E",
    studentId: "S-2005",
    date: "2025-04-20",
    type: "Endline",
    height: 117,
    weight: 19.2,
    bmi: 14.02,
    status: "At Risk",
    recordedBy: "Maria Reyes",
    notes: "Some improvement",
  },
  {
    id: "M-2006-B",
    studentId: "S-2006",
    date: "2025-01-15",
    type: "Baseline",
    height: 119,
    weight: 22.4,
    bmi: 15.79,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2006-E",
    studentId: "S-2006",
    date: "2025-04-20",
    type: "Endline",
    height: 122,
    weight: 24.1,
    bmi: 16.18,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2007-B",
    studentId: "S-2007",
    date: "2025-01-15",
    type: "Baseline",
    height: 113,
    weight: 14.8,
    bmi: 11.61,
    status: "Underweight",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2007-E",
    studentId: "S-2007",
    date: "2025-04-20",
    type: "Endline",
    height: 116,
    weight: 17.6,
    bmi: 13.08,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Needs additional intervention",
  },
  {
    id: "M-2008-B",
    studentId: "S-2008",
    date: "2025-01-15",
    type: "Baseline",
    height: 120,
    weight: 26.1,
    bmi: 18.13,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2008-E",
    studentId: "S-2008",
    date: "2025-04-20",
    type: "Endline",
    height: 123,
    weight: 26.8,
    bmi: 17.73,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2009-B",
    studentId: "S-2009",
    date: "2025-01-15",
    type: "Baseline",
    height: 115,
    weight: 17.8,
    bmi: 13.46,
    status: "At Risk",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-2009-E",
    studentId: "S-2009",
    date: "2025-04-20",
    type: "Endline",
    height: 118,
    weight: 19.9,
    bmi: 14.27,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },

  // Grade 3 - Ilang-Ilang
  {
    id: "M-3001-B",
    studentId: "S-3001",
    date: "2025-01-15",
    type: "Baseline",
    height: 122,
    weight: 25.1,
    bmi: 16.83,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3001-E",
    studentId: "S-3001",
    date: "2025-04-20",
    type: "Endline",
    height: 125,
    weight: 26.8,
    bmi: 17.13,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3002-B",
    studentId: "S-3002",
    date: "2025-01-15",
    type: "Baseline",
    height: 119,
    weight: 16.8,
    bmi: 11.89,
    status: "Underweight",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3002-E",
    studentId: "S-3002",
    date: "2025-04-20",
    type: "Endline",
    height: 122,
    weight: 19.3,
    bmi: 12.97,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Limited progress",
  },
  {
    id: "M-3003-B",
    studentId: "S-3003",
    date: "2025-01-15",
    type: "Baseline",
    height: 121,
    weight: 22.8,
    bmi: 15.58,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3003-E",
    studentId: "S-3003",
    date: "2025-04-20",
    type: "Endline",
    height: 124,
    weight: 24.6,
    bmi: 15.96,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3004-B",
    studentId: "S-3004",
    date: "2025-01-15",
    type: "Baseline",
    height: 123,
    weight: 26.9,
    bmi: 17.78,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3004-E",
    studentId: "S-3004",
    date: "2025-04-20",
    type: "Endline",
    height: 126,
    weight: 28.1,
    bmi: 17.69,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3005-B",
    studentId: "S-3005",
    date: "2025-01-15",
    type: "Baseline",
    height: 118,
    weight: 19.2,
    bmi: 13.79,
    status: "At Risk",
    recordedBy: "Maria Reyes",
    notes: "Wheat allergy noted",
  },
  {
    id: "M-3005-E",
    studentId: "S-3005",
    date: "2025-04-20",
    type: "Endline",
    height: 121,
    weight: 21.8,
    bmi: 14.87,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3006-B",
    studentId: "S-3006",
    date: "2025-01-15",
    type: "Baseline",
    height: 120,
    weight: 20.3,
    bmi: 14.1,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3006-E",
    studentId: "S-3006",
    date: "2025-04-20",
    type: "Endline",
    height: 123,
    weight: 22.1,
    bmi: 14.6,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3007-B",
    studentId: "S-3007",
    date: "2025-01-15",
    type: "Baseline",
    height: 117,
    weight: 15.9,
    bmi: 11.6,
    status: "Underweight",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3007-E",
    studentId: "S-3007",
    date: "2025-04-20",
    type: "Endline",
    height: 120,
    weight: 18.2,
    bmi: 12.64,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Severe underweight, urgent intervention needed",
  },
  {
    id: "M-3008-B",
    studentId: "S-3008",
    date: "2025-01-15",
    type: "Baseline",
    height: 124,
    weight: 28.9,
    bmi: 18.78,
    status: "Overweight",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-3008-E",
    studentId: "S-3008",
    date: "2025-04-20",
    type: "Endline",
    height: 127,
    weight: 29.3,
    bmi: 18.18,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },

  // Grade 4 - Orchid (additional records to reach 100+)
  {
    id: "M-4001-B",
    studentId: "S-4001",
    date: "2025-01-15",
    type: "Baseline",
    height: 128,
    weight: 23.1,
    bmi: 14.1,
    status: "At Risk",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4001-E",
    studentId: "S-4001",
    date: "2025-04-20",
    type: "Endline",
    height: 131,
    weight: 26.1,
    bmi: 15.21,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4002-B",
    studentId: "S-4002",
    date: "2025-01-15",
    type: "Baseline",
    height: 130,
    weight: 27.1,
    bmi: 16.05,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4002-E",
    studentId: "S-4002",
    date: "2025-04-20",
    type: "Endline",
    height: 133,
    weight: 29.2,
    bmi: 16.48,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4003-B",
    studentId: "S-4003",
    date: "2025-01-15",
    type: "Baseline",
    height: 129,
    weight: 28.9,
    bmi: 17.36,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4003-E",
    studentId: "S-4003",
    date: "2025-04-20",
    type: "Endline",
    height: 132,
    weight: 29.2,
    bmi: 16.78,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4004-B",
    studentId: "S-4004",
    date: "2025-01-15",
    type: "Baseline",
    height: 126,
    weight: 20.1,
    bmi: 12.67,
    status: "Underweight",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4004-E",
    studentId: "S-4004",
    date: "2025-04-20",
    type: "Endline",
    height: 129,
    weight: 23.3,
    bmi: 14.05,
    status: "At Risk",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4005-B",
    studentId: "S-4005",
    date: "2025-01-15",
    type: "Baseline",
    height: 131,
    weight: 27.8,
    bmi: 16.18,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4005-E",
    studentId: "S-4005",
    date: "2025-04-20",
    type: "Endline",
    height: 134,
    weight: 29.9,
    bmi: 16.64,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4006-B",
    studentId: "S-4006",
    date: "2025-01-15",
    type: "Baseline",
    height: 127,
    weight: 16.2,
    bmi: 10.05,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Soy allergy noted",
  },
  {
    id: "M-4006-E",
    studentId: "S-4006",
    date: "2025-04-20",
    type: "Endline",
    height: 130,
    weight: 19.3,
    bmi: 11.42,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Critical, needs immediate attention",
  },
  {
    id: "M-4007-B",
    studentId: "S-4007",
    date: "2025-01-15",
    type: "Baseline",
    height: 132,
    weight: 29.8,
    bmi: 17.08,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4007-E",
    studentId: "S-4007",
    date: "2025-04-20",
    type: "Endline",
    height: 135,
    weight: 30.1,
    bmi: 16.49,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4008-B",
    studentId: "S-4008",
    date: "2025-01-15",
    type: "Baseline",
    height: 129,
    weight: 23.6,
    bmi: 14.22,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-4008-E",
    studentId: "S-4008",
    date: "2025-04-20",
    type: "Endline",
    height: 132,
    weight: 25.7,
    bmi: 14.74,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },

  // Grade 5 - Camia
  {
    id: "M-5001-B",
    studentId: "S-5001",
    date: "2025-01-15",
    type: "Baseline",
    height: 135,
    weight: 29.2,
    bmi: 16.06,
    status: "Normal",
    recordedBy: "Maria Reyes",
    notes: "Seafood allergy noted",
  },
  {
    id: "M-5001-E",
    studentId: "S-5001",
    date: "2025-04-20",
    type: "Endline",
    height: 138,
    weight: 31.3,
    bmi: 16.45,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5002-B",
    studentId: "S-5002",
    date: "2025-01-15",
    type: "Baseline",
    height: 137,
    weight: 32.1,
    bmi: 17.07,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5002-E",
    studentId: "S-5002",
    date: "2025-04-20",
    type: "Endline",
    height: 140,
    weight: 34.2,
    bmi: 17.51,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5003-B",
    studentId: "S-5003",
    date: "2025-01-15",
    type: "Baseline",
    height: 136,
    weight: 33.8,
    bmi: 18.26,
    status: "Overweight",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5003-E",
    studentId: "S-5003",
    date: "2025-04-20",
    type: "Endline",
    height: 139,
    weight: 34.1,
    bmi: 17.63,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5004-B",
    studentId: "S-5004",
    date: "2025-01-15",
    type: "Baseline",
    height: 133,
    weight: 23.4,
    bmi: 13.22,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Dairy allergy noted",
  },
  {
    id: "M-5004-E",
    studentId: "S-5004",
    date: "2025-04-20",
    type: "Endline",
    height: 136,
    weight: 26.2,
    bmi: 14.16,
    status: "At Risk",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5005-B",
    studentId: "S-5005",
    date: "2025-01-15",
    type: "Baseline",
    height: 134,
    weight: 28.1,
    bmi: 15.62,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5005-E",
    studentId: "S-5005",
    date: "2025-04-20",
    type: "Endline",
    height: 137,
    weight: 30.2,
    bmi: 16.08,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5006-B",
    studentId: "S-5006",
    date: "2025-01-15",
    type: "Baseline",
    height: 136,
    weight: 29.8,
    bmi: 16.08,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5006-E",
    studentId: "S-5006",
    date: "2025-04-20",
    type: "Endline",
    height: 139,
    weight: 32.1,
    bmi: 16.61,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5007-B",
    studentId: "S-5007",
    date: "2025-01-15",
    type: "Baseline",
    height: 138,
    weight: 33.1,
    bmi: 17.36,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5007-E",
    studentId: "S-5007",
    date: "2025-04-20",
    type: "Endline",
    height: 141,
    weight: 33.4,
    bmi: 16.8,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-5008-B",
    studentId: "S-5008",
    date: "2025-01-15",
    type: "Baseline",
    height: 132,
    weight: 21.8,
    bmi: 12.51,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Fish allergy noted",
  },
  {
    id: "M-5008-E",
    studentId: "S-5008",
    date: "2025-04-20",
    type: "Endline",
    height: 135,
    weight: 24.1,
    bmi: 13.21,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Still significantly underweight",
  },

  // Grade 6 - Daisy
  {
    id: "M-6001-B",
    studentId: "S-6001",
    date: "2025-01-15",
    type: "Baseline",
    height: 142,
    weight: 32.8,
    bmi: 16.29,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6001-E",
    studentId: "S-6001",
    date: "2025-04-20",
    type: "Endline",
    height: 145,
    weight: 35.1,
    bmi: 16.68,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6002-B",
    studentId: "S-6002",
    date: "2025-01-15",
    type: "Baseline",
    height: 141,
    weight: 35.9,
    bmi: 18.08,
    status: "Overweight",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6002-E",
    studentId: "S-6002",
    date: "2025-04-20",
    type: "Endline",
    height: 144,
    weight: 35.6,
    bmi: 17.13,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6003-B",
    studentId: "S-6003",
    date: "2025-01-15",
    type: "Baseline",
    height: 139,
    weight: 27.1,
    bmi: 14.01,
    status: "Normal",
    recordedBy: "Maria Reyes",
    notes: "Citrus allergy noted",
  },
  {
    id: "M-6003-E",
    studentId: "S-6003",
    date: "2025-04-20",
    type: "Endline",
    height: 142,
    weight: 29.6,
    bmi: 14.69,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6004-B",
    studentId: "S-6004",
    date: "2025-01-15",
    type: "Baseline",
    height: 137,
    weight: 25.6,
    bmi: 13.66,
    status: "At Risk",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6004-E",
    studentId: "S-6004",
    date: "2025-04-20",
    type: "Endline",
    height: 140,
    weight: 28.8,
    bmi: 14.69,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6005-B",
    studentId: "S-6005",
    date: "2025-01-15",
    type: "Baseline",
    height: 140,
    weight: 29.3,
    bmi: 14.95,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6005-E",
    studentId: "S-6005",
    date: "2025-04-20",
    type: "Endline",
    height: 143,
    weight: 31.7,
    bmi: 15.48,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6006-B",
    studentId: "S-6006",
    date: "2025-01-15",
    type: "Baseline",
    height: 143,
    weight: 34.1,
    bmi: 16.67,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6006-E",
    studentId: "S-6006",
    date: "2025-04-20",
    type: "Endline",
    height: 146,
    weight: 34.8,
    bmi: 16.35,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6007-B",
    studentId: "S-6007",
    date: "2025-01-15",
    type: "Baseline",
    height: 135,
    weight: 22.9,
    bmi: 12.56,
    status: "Underweight",
    recordedBy: "Maria Reyes",
    notes: "Chocolate allergy noted",
  },
  {
    id: "M-6007-E",
    studentId: "S-6007",
    date: "2025-04-20",
    type: "Endline",
    height: 138,
    weight: 26.1,
    bmi: 13.72,
    status: "At Risk",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6008-B",
    studentId: "S-6008",
    date: "2025-01-15",
    type: "Baseline",
    height: 141,
    weight: 31.9,
    bmi: 16.05,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
  {
    id: "M-6008-E",
    studentId: "S-6008",
    date: "2025-04-20",
    type: "Endline",
    height: 144,
    weight: 33.8,
    bmi: 16.28,
    status: "Normal",
    recordedBy: "Maria Reyes",
  },
];

export interface FeedingRecord {
  id: string;
  date: string;
  studentId: string;
  grade: string;
  section: string;
  present: boolean;
  absent: boolean;
  receivedMeal: boolean;
  mealType: "Breakfast" | "Lunch" | "Snack";
  recordedBy: string;
  notes?: string;
}

export const feedingRecords: FeedingRecord[] = [
  // January 2025 feeding records - multiple days
  // Grade 1 - Sampaguita - January 15
  {
    id: "F-20250115-S-1001",
    date: "2025-01-15",
    studentId: "S-1001",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250115-S-1002",
    date: "2025-01-15",
    studentId: "S-1002",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250115-S-1003",
    date: "2025-01-15",
    studentId: "S-1003",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250115-S-1004",
    date: "2025-01-15",
    studentId: "S-1004",
    grade: "Grade 1",
    section: "Sampaguita",
    present: false,
    absent: true,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
    notes: "Sick leave",
  },
  {
    id: "F-20250115-S-1005",
    date: "2025-01-15",
    studentId: "S-1005",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250115-S-1006",
    date: "2025-01-15",
    studentId: "S-1006",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250115-S-1007",
    date: "2025-01-15",
    studentId: "S-1007",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250115-S-1008",
    date: "2025-01-15",
    studentId: "S-1008",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
    notes: "Allergic reaction concern",
  },
  {
    id: "F-20250115-S-1009",
    date: "2025-01-15",
    studentId: "S-1009",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },

  // Grade 2 - Rosal - January 15
  {
    id: "F-20250115-S-2001",
    date: "2025-01-15",
    studentId: "S-2001",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250115-S-2002",
    date: "2025-01-15",
    studentId: "S-2002",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250115-S-2003",
    date: "2025-01-15",
    studentId: "S-2003",
    grade: "Grade 2",
    section: "Rosal",
    present: false,
    absent: true,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Carlos Reyes",
    notes: "Family emergency",
  },
  {
    id: "F-20250115-S-2004",
    date: "2025-01-15",
    studentId: "S-2004",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250115-S-2005",
    date: "2025-01-15",
    studentId: "S-2005",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Carlos Reyes",
    notes: "Allergy concern",
  },
  {
    id: "F-20250115-S-2006",
    date: "2025-01-15",
    studentId: "S-2006",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250115-S-2007",
    date: "2025-01-15",
    studentId: "S-2007",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250115-S-2008",
    date: "2025-01-15",
    studentId: "S-2008",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250115-S-2009",
    date: "2025-01-15",
    studentId: "S-2009",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Carlos Reyes",
  },

  // January 16 - varied attendance
  {
    id: "F-20250116-S-1001",
    date: "2025-01-16",
    studentId: "S-1001",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250116-S-1002",
    date: "2025-01-16",
    studentId: "S-1002",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250116-S-1003",
    date: "2025-01-16",
    studentId: "S-1003",
    grade: "Grade 1",
    section: "Sampaguita",
    present: false,
    absent: true,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Anna Santos",
    notes: "Late arrival",
  },
  {
    id: "F-20250116-S-1004",
    date: "2025-01-16",
    studentId: "S-1004",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Anna Santos",
    notes: "Egg allergy",
  },
  {
    id: "F-20250116-S-1005",
    date: "2025-01-16",
    studentId: "S-1005",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250116-S-1006",
    date: "2025-01-16",
    studentId: "S-1006",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250116-S-1007",
    date: "2025-01-16",
    studentId: "S-1007",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250116-S-1008",
    date: "2025-01-16",
    studentId: "S-1008",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Anna Santos",
    notes: "Milk allergy",
  },
  {
    id: "F-20250116-S-1009",
    date: "2025-01-16",
    studentId: "S-1009",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Anna Santos",
  },

  // January 20 - Monday
  {
    id: "F-20250120-S-3001",
    date: "2025-01-20",
    studentId: "S-3001",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250120-S-3002",
    date: "2025-01-20",
    studentId: "S-3002",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250120-S-3003",
    date: "2025-01-20",
    studentId: "S-3003",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250120-S-3004",
    date: "2025-01-20",
    studentId: "S-3004",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: false,
    absent: true,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
    notes: "Medical appointment",
  },
  {
    id: "F-20250120-S-3005",
    date: "2025-01-20",
    studentId: "S-3005",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
    notes: "Wheat allergy",
  },
  {
    id: "F-20250120-S-3006",
    date: "2025-01-20",
    studentId: "S-3006",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250120-S-3007",
    date: "2025-01-20",
    studentId: "S-3007",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250120-S-3008",
    date: "2025-01-20",
    studentId: "S-3008",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },

  // January 21 - varied patterns
  {
    id: "F-20250121-S-4001",
    date: "2025-01-21",
    studentId: "S-4001",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250121-S-4002",
    date: "2025-01-21",
    studentId: "S-4002",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250121-S-4003",
    date: "2025-01-21",
    studentId: "S-4003",
    grade: "Grade 4",
    section: "Orchid",
    present: false,
    absent: true,
    receivedMeal: false,
    mealType: "Snack",
    recordedBy: "Elena Santos",
    notes: "Field trip",
  },
  {
    id: "F-20250121-S-4004",
    date: "2025-01-21",
    studentId: "S-4004",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250121-S-4005",
    date: "2025-01-21",
    studentId: "S-4005",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250121-S-4006",
    date: "2025-01-21",
    studentId: "S-4006",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Snack",
    recordedBy: "Elena Santos",
    notes: "Soy allergy",
  },
  {
    id: "F-20250121-S-4007",
    date: "2025-01-21",
    studentId: "S-4007",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250121-S-4008",
    date: "2025-01-21",
    studentId: "S-4008",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Elena Santos",
  },

  // January 22 - normal day
  {
    id: "F-20250122-S-5001",
    date: "2025-01-22",
    studentId: "S-5001",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Rosa Mendoza",
    notes: "Seafood allergy",
  },
  {
    id: "F-20250122-S-5002",
    date: "2025-01-22",
    studentId: "S-5002",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Rosa Mendoza",
  },
  {
    id: "F-20250122-S-5003",
    date: "2025-01-22",
    studentId: "S-5003",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Rosa Mendoza",
  },
  {
    id: "F-20250122-S-5004",
    date: "2025-01-22",
    studentId: "S-5004",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Rosa Mendoza",
    notes: "Dairy allergy",
  },
  {
    id: "F-20250122-S-5005",
    date: "2025-01-22",
    studentId: "S-5005",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Rosa Mendoza",
  },
  {
    id: "F-20250122-S-5006",
    date: "2025-01-22",
    studentId: "S-5006",
    grade: "Grade 5",
    section: "Camia",
    present: false,
    absent: true,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Rosa Mendoza",
    notes: "Sports event",
  },
  {
    id: "F-20250122-S-5007",
    date: "2025-01-22",
    studentId: "S-5007",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Rosa Mendoza",
  },
  {
    id: "F-20250122-S-5008",
    date: "2025-01-22",
    studentId: "S-5008",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Rosa Mendoza",
    notes: "Fish allergy",
  },

  // January 23 - high attendance
  {
    id: "F-20250123-S-6001",
    date: "2025-01-23",
    studentId: "S-6001",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250123-S-6002",
    date: "2025-01-23",
    studentId: "S-6002",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250123-S-6003",
    date: "2025-01-23",
    studentId: "S-6003",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
    notes: "Citrus allergy",
  },
  {
    id: "F-20250123-S-6004",
    date: "2025-01-23",
    studentId: "S-6004",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250123-S-6005",
    date: "2025-01-23",
    studentId: "S-6005",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250123-S-6006",
    date: "2025-01-23",
    studentId: "S-6006",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250123-S-6007",
    date: "2025-01-23",
    studentId: "S-6007",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
    notes: "Chocolate allergy",
  },
  {
    id: "F-20250123-S-6008",
    date: "2025-01-23",
    studentId: "S-6008",
    grade: "Grade 6",
    section: "Daisy",
    present: false,
    absent: true,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
    notes: "Overslept",
  },

  // February records - different month
  {
    id: "F-20250201-S-1001",
    date: "2025-02-01",
    studentId: "S-1001",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250201-S-1002",
    date: "2025-02-01",
    studentId: "S-1002",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250201-S-1003",
    date: "2025-02-01",
    studentId: "S-1003",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250201-S-1004",
    date: "2025-02-01",
    studentId: "S-1004",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
    notes: "Egg allergy",
  },
  {
    id: "F-20250201-S-1005",
    date: "2025-02-01",
    studentId: "S-1005",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250201-S-1006",
    date: "2025-02-01",
    studentId: "S-1006",
    grade: "Grade 1",
    section: "Sampaguita",
    present: false,
    absent: true,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
    notes: "Fever",
  },
  {
    id: "F-20250201-S-1007",
    date: "2025-02-01",
    studentId: "S-1007",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },
  {
    id: "F-20250201-S-1008",
    date: "2025-02-01",
    studentId: "S-1008",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
    notes: "Milk allergy",
  },
  {
    id: "F-20250201-S-1009",
    date: "2025-02-01",
    studentId: "S-1009",
    grade: "Grade 1",
    section: "Sampaguita",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Anna Santos",
  },

  // February 3 - Monday
  {
    id: "F-20250203-S-2001",
    date: "2025-02-03",
    studentId: "S-2001",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250203-S-2002",
    date: "2025-02-03",
    studentId: "S-2002",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250203-S-2003",
    date: "2025-02-03",
    studentId: "S-2003",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250203-S-2004",
    date: "2025-02-03",
    studentId: "S-2004",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250203-S-2005",
    date: "2025-02-03",
    studentId: "S-2005",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Snack",
    recordedBy: "Carlos Reyes",
    notes: "Shellfish allergy",
  },
  {
    id: "F-20250203-S-2006",
    date: "2025-02-03",
    studentId: "S-2006",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250203-S-2007",
    date: "2025-02-03",
    studentId: "S-2007",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250203-S-2008",
    date: "2025-02-03",
    studentId: "S-2008",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Carlos Reyes",
  },
  {
    id: "F-20250203-S-2009",
    date: "2025-02-03",
    studentId: "S-2009",
    grade: "Grade 2",
    section: "Rosal",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Snack",
    recordedBy: "Carlos Reyes",
  },

  // February 5 - varied patterns
  {
    id: "F-20250205-S-3001",
    date: "2025-02-05",
    studentId: "S-3001",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250205-S-3002",
    date: "2025-02-05",
    studentId: "S-3002",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250205-S-3003",
    date: "2025-02-05",
    studentId: "S-3003",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250205-S-3004",
    date: "2025-02-05",
    studentId: "S-3004",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250205-S-3005",
    date: "2025-02-05",
    studentId: "S-3005",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
    notes: "Wheat allergy",
  },
  {
    id: "F-20250205-S-3006",
    date: "2025-02-05",
    studentId: "S-3006",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: false,
    absent: true,
    receivedMeal: false,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
    notes: "School activity",
  },
  {
    id: "F-20250205-S-3007",
    date: "2025-02-05",
    studentId: "S-3007",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },
  {
    id: "F-20250205-S-3008",
    date: "2025-02-05",
    studentId: "S-3008",
    grade: "Grade 3",
    section: "Ilang-Ilang",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Lunch",
    recordedBy: "Maria Cruz",
  },

  // February 7 - more records to reach 100+
  {
    id: "F-20250207-S-4001",
    date: "2025-02-07",
    studentId: "S-4001",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250207-S-4002",
    date: "2025-02-07",
    studentId: "S-4002",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250207-S-4003",
    date: "2025-02-07",
    studentId: "S-4003",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250207-S-4004",
    date: "2025-02-07",
    studentId: "S-4004",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250207-S-4005",
    date: "2025-02-07",
    studentId: "S-4005",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250207-S-4006",
    date: "2025-02-07",
    studentId: "S-4006",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Elena Santos",
    notes: "Soy allergy",
  },
  {
    id: "F-20250207-S-4007",
    date: "2025-02-07",
    studentId: "S-4007",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250207-S-4008",
    date: "2025-02-07",
    studentId: "S-4008",
    grade: "Grade 4",
    section: "Orchid",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Elena Santos",
  },
  {
    id: "F-20250207-S-5001",
    date: "2025-02-07",
    studentId: "S-5001",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Rosa Mendoza",
    notes: "Seafood allergy",
  },
  {
    id: "F-20250207-S-5002",
    date: "2025-02-07",
    studentId: "S-5002",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Rosa Mendoza",
  },
  {
    id: "F-20250207-S-5003",
    date: "2025-02-07",
    studentId: "S-5003",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Rosa Mendoza",
  },
  {
    id: "F-20250207-S-5004",
    date: "2025-02-07",
    studentId: "S-5004",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Rosa Mendoza",
    notes: "Dairy allergy",
  },
  {
    id: "F-20250207-S-5005",
    date: "2025-02-07",
    studentId: "S-5005",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Rosa Mendoza",
  },
  {
    id: "F-20250207-S-5006",
    date: "2025-02-07",
    studentId: "S-5006",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Rosa Mendoza",
  },
  {
    id: "F-20250207-S-5007",
    date: "2025-02-07",
    studentId: "S-5007",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Rosa Mendoza",
  },
  {
    id: "F-20250207-S-5008",
    date: "2025-02-07",
    studentId: "S-5008",
    grade: "Grade 5",
    section: "Camia",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Rosa Mendoza",
    notes: "Fish allergy",
  },
  {
    id: "F-20250207-S-6001",
    date: "2025-02-07",
    studentId: "S-6001",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250207-S-6002",
    date: "2025-02-07",
    studentId: "S-6002",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250207-S-6003",
    date: "2025-02-07",
    studentId: "S-6003",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
    notes: "Citrus allergy",
  },
  {
    id: "F-20250207-S-6004",
    date: "2025-02-07",
    studentId: "S-6004",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250207-S-6005",
    date: "2025-02-07",
    studentId: "S-6005",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250207-S-6006",
    date: "2025-02-07",
    studentId: "S-6006",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
  {
    id: "F-20250207-S-6007",
    date: "2025-02-07",
    studentId: "S-6007",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: false,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
    notes: "Chocolate allergy",
  },
  {
    id: "F-20250207-S-6008",
    date: "2025-02-07",
    studentId: "S-6008",
    grade: "Grade 6",
    section: "Daisy",
    present: true,
    absent: false,
    receivedMeal: true,
    mealType: "Breakfast",
    recordedBy: "Carmen Lopez",
  },
];
