/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedingRouteImport } from './routes/feeding'
import { Route as IndexRouteImport } from './routes/index'

const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedingRoute = FeedingRouteImport.update({
  id: '/feeding',
  path: '/feeding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feeding': typeof FeedingRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/nutrition': typeof NutritionRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/users': typeof UsersRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feeding': typeof FeedingRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/nutrition': typeof NutritionRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/users': typeof UsersRoute
  '/validation': typeof ValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feeding': typeof FeedingRoute
  '/login': typeof LoginRoute
  '/measurements': typeof MeasurementsRoute
  '/nutrition': typeof NutritionRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/students': typeof StudentsRoute
  '/users': typeof UsersRoute
  '/validation': typeof ValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feeding'
    | '/login'
    | '/measurements'
    | '/nutrition'
    | '/reports'
    | '/settings'
    | '/students'
    | '/users'
    | '/validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feeding'
    | '/login'
    | '/measurements'
    | '/nutrition'
    | '/reports'
    | '/settings'
    | '/students'
    | '/users'
    | '/validation'
  id:
    | '__root__'
    | '/'
    | '/feeding'
    | '/login'
    | '/measurements'
    | '/nutrition'
    | '/reports'
    | '/settings'
    | '/students'
    | '/users'
    | '/validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedingRoute: typeof FeedingRoute
  LoginRoute: typeof LoginRoute
  MeasurementsRoute: typeof MeasurementsRoute
  NutritionRoute: typeof NutritionRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StudentsRoute: typeof StudentsRoute
  UsersRoute: typeof UsersRoute
  ValidationRoute: typeof ValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeding': {
      id: '/feeding'
      path: '/feeding'
      fullPath: '/feeding'
      preLoaderRoute: typeof FeedingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedingRoute: FeedingRoute,
  LoginRoute: LoginRoute,
  MeasurementsRoute: MeasurementsRoute,
  NutritionRoute: NutritionRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StudentsRoute: StudentsRoute,
  UsersRoute: UsersRoute,
  ValidationRoute: ValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
